package com.internship.tool.entity;

import jakarta.persistence.*;
import lombok.*;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.LocalDateTime;

/**
 * Incident Entity — maps to the "incidents" table in PostgreSQL.
 * Every field here must match V1__init.sql exactly.
 *
 * Day 2 — Java Developer 1
 */
@Entity
@Table(name = "incidents")
@EntityListeners(AuditingEntityListener.class)  // enables @CreatedDate / @LastModifiedDate
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Incident {

    // ── Primary Key ───────────────────────────────────────────────
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // ── Core Fields ───────────────────────────────────────────────

    @Column(name = "title", nullable = false, length = 255)
    private String title;

    @Column(name = "description", nullable = false, columnDefinition = "TEXT")
    private String description;

    @Column(name = "incident_type", nullable = false, length = 100)
    private String incidentType;       // e.g. "Security Breach", "Data Loss", "Phishing"

    @Column(name = "severity", nullable = false, length = 20)
    private String severity;           // LOW | MEDIUM | HIGH | CRITICAL

    @Column(name = "status", nullable = false, length = 20)
    private String status;             // OPEN | IN_PROGRESS | RESOLVED | CLOSED

    @Column(name = "reported_by", nullable = false, length = 100)
    private String reportedBy;         // name or username of the person who reported

    @Column(name = "assigned_to", length = 100)
    private String assignedTo;         // name or username of assigned investigator

    @Column(name = "location", length = 255)
    private String location;           // where the incident happened

    @Column(name = "evidence_url", length = 500)
    private String evidenceUrl;        // link to uploaded evidence file

    @Column(name = "incident_date", nullable = false)
    private LocalDateTime incidentDate; // when the incident actually occurred

    @Column(name = "resolved_date")
    private LocalDateTime resolvedDate; // when it was resolved (null if not yet)

    // ── AI Generated Fields ───────────────────────────────────────
    @Column(name = "ai_description", columnDefinition = "TEXT")
    private String aiDescription;      // generated by Flask /describe endpoint

    @Column(name = "ai_recommendation", columnDefinition = "TEXT")
    private String aiRecommendation;   // generated by Flask /recommend endpoint

    @Column(name = "ai_generated_at")
    private LocalDateTime aiGeneratedAt; // when AI last processed this record

    // ── Soft Delete ───────────────────────────────────────────────
    @Column(name = "is_deleted", nullable = false)
    @Builder.Default
    private Boolean isDeleted = false;  // true = soft deleted, never shown in results

    // ── Audit Fields (auto-filled by Spring) ──────────────────────
    @CreatedDate
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @LastModifiedDate
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;
}
